<a href="https://colab.research.google.com/github/gizemburun/LSTM_experiments/blob/univariate-LSTM-experimentation/Experiment_gizem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import keras
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
import pandas as pd


Create convert function time series data to sample

In [ ]:
def split_sequence (sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    end_ix = i + n_steps

    if end_ix > len(sequence)-1:
      break

    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)

  return array(X), array(y)

upload file

In [ ]:
from google.colab import files
uploaded = files.upload()

# To store dataset in a Pandas Dataframe
import io
df2 = pd.read_csv(io.BytesIO(uploaded['experiment_gizem_1.csv']))


Saving experiment_gizem_1.csv to experiment_gizem_1.csv


example time series data

In [ ]:
df2

Tor
0   0.451575
1   0.529574
2   0.455680
3   0.525469
4   0.455680
5   0.529574
6   0.451575
7   0.517258
8   0.447469
9   0.513153
10  0.447469
11  0.529574
12  0.451575
13  0.529574
14  0.455680
15  0.529574
16  0.463890
17  0.525469
18  0.451575
19  0.517258
20  0.443364
21  0.517258
22  0.455680
23  0.525469
24  0.459785
25  0.533679
26  0.459785
27  0.533679

applicaiton of split function

In [ ]:
n_steps = 3

X, y = split_sequence(df2["Tor"], n_steps)

for i in range(len(X)):
  print (X[i],y[i])

[0.451575 0.529574 0.45568 ] 0.525469
[0.529574 0.45568  0.525469] 0.45568000000000003
[0.45568  0.525469 0.45568 ] 0.529574
[0.525469 0.45568  0.529574] 0.451575
[0.45568  0.529574 0.451575] 0.517258
[0.529574 0.451575 0.517258] 0.44746899999999995
[0.451575 0.517258 0.447469] 0.513153
[0.517258 0.447469 0.513153] 0.44746899999999995
[0.447469 0.513153 0.447469] 0.529574
[0.513153 0.447469 0.529574] 0.451575
[0.447469 0.529574 0.451575] 0.529574
[0.529574 0.451575 0.529574] 0.45568000000000003
[0.451575 0.529574 0.45568 ] 0.529574
[0.529574 0.45568  0.529574] 0.46388999999999997
[0.45568  0.529574 0.46389 ] 0.525469
[0.529574 0.46389  0.525469] 0.451575
[0.46389  0.525469 0.451575] 0.517258
[0.525469 0.451575 0.517258] 0.44336400000000004
[0.451575 0.517258 0.443364] 0.517258
[0.517258 0.443364 0.517258] 0.45568000000000003
[0.443364 0.517258 0.45568 ] 0.525469
[0.517258 0.45568  0.525469] 0.45978500000000005
[0.45568  0.525469 0.459785] 0.533679
[0.525469 0.459785 0.533679] 0.4597850

create LSTM model

In [ ]:
n_features = 1
X = X.reshape(X.shape[0], X.shape[1], n_features)

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps,n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')



train model

In [ ]:
model.fit(X, y, epochs=200, verbose=0)

test model

In [8]:
x_input=array([0.451575, 0.529574, 0.45568])
x_input = x_input.reshape(1,n_steps,n_features)
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[0.48445284]]
